apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-transaction-service
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-transaction-service
  template:
    metadata:
      labels:
        app: dev-transaction-service
    spec:
      containers:
      - name: dev-transaction-service
        image: mohamedsamir170/transaction-service:dev
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: insta-pay-config-dev
            
        ports:
        - containerPort: 5000

        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: dev-transaction-service
  namespace: development
spec:
  type: ClusterIP
  selector:
    app: dev-transaction-service
  ports:
    - port: 5000
      targetPort: 5000
